import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Evaluación TRC",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="min-h-screen flex flex-col">
        <NuqsAdapter>
          {/* Header */}
          <header className="w-full">
            <Image 
              src="https://res.cloudinary.com/dj9848zoy/image/upload/v1752721055/Header_xippn8.png"
              alt="Header"
              width={1920}
              height={200}
              className="w-full h-auto object-cover"
              priority
            />
          </header>

          {/* Main Content */}
          <main className="flex-1">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>

          {/* Footer */}
          <footer className="w-full mt-auto">
            <Image 
              src="https://res.cloudinary.com/dj9848zoy/image/upload/v1752721049/Footer_yfdur6.png"
              alt="Footer"
              width={1920}
              height={150}
              className="w-full h-auto object-cover"
            />
          </footer>

          <Toaster />
        </NuqsAdapter>
      </body>
    </html>
  );
}
